### ISSUE TITLE
点击图片预览崩溃啊

### ISSUE THREAD

**Issue by renhuan** [jeasonlzy0216/NineGridView#53]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.zht/com.lzy.ninegrid.preview.ImagePreviewActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                   at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class <unknown>
                                                                Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class <unknown>

**Comment by renhuan** [comment]
解决了，这个问题是由于主项目覆盖了库项目的xml所致，如果主项目中的某个xml里定义了一个跟库项目中的xml同名的xml，那么库中的xml将会被覆盖。
