### ISSUE TITLE
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by weituotian** [jeasonlzy0216/NineGridView#59]
```
W/System.err: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
W/System.err:     at com.lzy.ninegridview.model.news.NewsActivity$1.onResponse(NewsActivity.java:60)
W/System.err:     at com.lzy.ninegridview.model.news.NewsActivity$1.onResponse(NewsActivity.java:55)
W/System.err:     at com.lzy.okhttputils.request.BaseRequest$4.run(BaseRequest.java:484)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:135)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5296)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

这个api失效了
```
public static final String CHANNEL = "http://apis.baidu.com/showapi_open_bus/channel_news/channel_news";
```

**Comment by nikhilgodhani08** [comment]
HI, me also getting this error .. so, any solution for this?

**Comment by 1035813893** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
