### ISSUE TITLE
点击预览图崩溃,报空指针异常

### ISSUE THREAD

**Issue by clbDream** [jeasonlzy0216/NineGridView#73]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.viewpager.widget.ViewPager.setAdapter(androidx.viewpager.widget.PagerAdapter)' on a null object reference
        at com.lzy.ninegrid.preview.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:58)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)

**Comment by mjl1564159881** [comment]
我跟你的一样

**Comment by Jack-bin183** [comment]
同求解  一样的代码在另一个APP里面正常  就离谱

**Comment by Jack-bin183** [comment]
解决了   把库拉到本地  然后手动迁移到安卓x     具体是啥原因不清楚
